### ISSUE TITLE
Disable/Enable extension causes Gnome-Shell crash under Wayland

### ISSUE THREAD

**Issue by gogi983** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#1]
Hi Timur,
As I commented on the extensions web-site, disabling/enabling the extension makes Gnome-Shell crash and one have to log in again (at least under Wayland, didn't try under X11...), and second is that with extension activated screenshots go well to the set path, but sound from "screenshotting" is muted. 

About crash issue, executing "journalctl /usr/bin/gnome-shell" gives me only the following two relevant lines : 

```
march 13 20:08:25 debtrfs gnome-shell[23362]: Failed to apply DRM plane transform 0: Invalid argument
march 13 20:08:25 debtrfs org.gnome.Shell.desktop[23362]: glamor: EGL version 1.4 (DRI2):
```
I have no given log lines about screeshotting sound muted...
By the way FYI, I'm on Debian Sid with Gnome-Shell 3.22 if that may help.

Regards.

**Comment by gogi983** [comment]
Hi Timur,

Just to give further info, I actually tested it under X11, and it has the same behaviour, the only difference is that uder X11 Gnome-Shell doesn't crash but only looks like refreshing, the same when one enters command : 

`$ gnome-shell --replace`

And no relevant log lines under X11.

**Comment by kiyui** [comment]
I've updated the repository locally and am waiting for GNOME to review the updated extension and publish it. Meanwhile you can clone the repository and put the extension folder in `~/.local/share/gnome-shell/extensions/` and replace the previous version. It should fix the crashing issue.

**Comment by gogi983** [comment]
Ok I'm gonna give it a try and tell you if it's correct now.

**Comment by gogi983** [comment]
Just tried it and it seems to be ok for now, I'll let you know these days if it's definitely ok.

And what about sound muted when takinf screeshots? Do you have any idea? Maybe extension overriding global settings causes this?

**Comment by kiyui** [comment]
Good to know, for me the issue right now with this version is disabling does not apply until a reboot. Further testing required on my part.

As for the sound, I am not sure why there is none as issuing `gnome-screenshot` from the command line does indeed trigger the sound.

Thanks for reporting and testing, let me know if no issues in the next few days so this issue can be closed.

**Comment by gogi983** [comment]
You mean you can't eventually disable the extension without rebooting? I don't have that kind of issue here.
By the way I tried again to enable/disable several times right now and it's working fine now, considering this. We just need to solve the sound issue now.

**Comment by kiyui** [comment]
I've submitted a hack that enables sound, but still can't figure out why the screenshot command itself does not play the sound. You can test the extension while it awaits review on the GNOME Extension website.

**Comment by gogi983** [comment]
Well, it is still not working for me... :/
I also noticed right now that it isn't naming anymore the created screeshot with time and date.

**Comment by kiyui** [comment]
Ah, that's weird. Do you have `paplay` installed? It should come with PulseAudio and be present on all GNOME installations that I've tested so far. Yes, I'm aware of the screenshot name (Using UNIX time at the moment). I could fix that but decided that if I do, I should make sure localization works so I don't have to do the same work twice. I'll handle that under a separate issue.

**Comment by gogi983** [comment]
> Ah, that's weird. Do you have paplay installed?

No, there isn't such package in Debian repos.

For the screenshot name, personally it doesn't matter to me as I use to rename screenshots I take so this is not really some kind of issue for me, but may be for other people.

**Comment by kiyui** [comment]
Odd, it should be under something like `pulseaudio-utils`. I'll see if I can find a better workaround for sound, this is just a hack at the moment. Do you have the file `/usr/share/sounds/freedesktop/stereo/camera-shutter.oga`?

**Comment by gogi983** [comment]
> Do you have the file /usr/share/sounds/freedesktop/stereo/camera-shutter.oga?

Yes I've got this file, it is provided by "sound-theme-freedesktop" package.

> I'll see if I can find a better workaround for sound, this is just a hack at the moment.

No problem, it isn't an emergency anyway ;)

**Comment by kiyui** [comment]
I've pushed a newer version that seems to work with sound and correct name for me, although I have no idea why it works :confused: Please try and thanks so much for all the help!

**Comment by gogi983** [comment]
Well I feel really confused but it still doesn't work for me 😕
Neither the sound nor renaming... I wish I could help you to figure out why it is not working but I haven't any programming skill... 
Anyway you know, at the origin this app under gnome is a real piece of shit by itself, even the GUI app doesn't behave like built-in shortcuts, and none of them does take into account options from dconf, so it's a total mess and I understand you have so much trouble to figure out easily what's going wrong...

**Comment by kiyui** [comment]
Here's the latest version: [screenshotlocations.timur@linux.com.zip](https://github.com/TimurKiyivinski/gnome-shell-screenshotlocations-extension/files/858162/screenshotlocations.timur.linux.com.zip)

To use it, delete your current version under GNOME Tweak Tools, reopen Tweak Tool and import this ZIP. You should receive a prompt to restart shell, just do so. Then under Tweak Tool, enable the extension. It should work, it worked on all my friend's GNOME installations. Perhaps you just didn't restart shell so the newer version just didn't take effect?

**Comment by gogi983** [comment]
You're damn right ;) I just forgot to restart gnome-shell, as I'm running under Wayland on my Debian Sid I thought it would be enough to just toggle disable/enable the extension but it wasn't indeed...

Anyway congratulations for all the work you've done to bring this extension functional and for finally solving the path issue with this crappy gnome-app.

Best regards.
